# Generated by Django 4.2.1 on 2023-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankomat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.IntegerField(),
        ),
    ]
